---
- name: Setup httpd server
  hosts: localhost
  become: false
  tasks:
   - name: Install httpd
     ansible.builtin.package:
      name: httpd
      state: present
     become: true
   - name: Copy file from base system to target node
     ansible.builtin.copy:
      src: /root/test.html
      dest: /var/www/html/lw.html

   - name: Start service httpd, if not started
     ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
