---
- name: Ansible AWX test with Playbook
  hosts: all
  connection: local
  gather_facts: false

  tasks:
  - name: Hello World!
    shell: echo "Hi! Tower is working!"

  - name: collect facts about system services
    service_facts:
    register: services_state

  - name: Debug
    debug:
      var: services_state
  
  - name: Httpd Install 
    yum: 
      name: httpd
      state: present
    become: true